/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AbilitySet {
  'id' : bigint,
  'requiredLevel' : bigint,
  'name' : string,
  'description' : string,
}
export interface MatchResult { 'xpAwarded' : bigint, 'didWin' : boolean }
export interface PlayerProfile {
  'principal' : Principal,
  'name' : string,
  'level' : bigint,
  'experience' : bigint,
  'unlockedAbilities' : Array<AbilitySet>,
  'avatarUrl' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'awardMatchXp' : ActorMethod<[boolean], MatchResult>,
  'getAbilityById' : ActorMethod<[bigint], [] | [AbilitySet]>,
  'getAvailableAbilities' : ActorMethod<[], Array<AbilitySet>>,
  'getCallerPlayerProfile' : ActorMethod<[], [] | [PlayerProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPlayerProfile' : ActorMethod<[Principal], [] | [PlayerProfile]>,
  'initializeAbilities' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerPlayerProfile' : ActorMethod<[PlayerProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];