/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MatchResult = IDL.Record({
  'xpAwarded' : IDL.Nat,
  'didWin' : IDL.Bool,
});
export const AbilitySet = IDL.Record({
  'id' : IDL.Nat,
  'requiredLevel' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const PlayerProfile = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'level' : IDL.Nat,
  'experience' : IDL.Nat,
  'unlockedAbilities' : IDL.Vec(AbilitySet),
  'avatarUrl' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'awardMatchXp' : IDL.Func([IDL.Bool], [MatchResult], []),
  'getAbilityById' : IDL.Func([IDL.Nat], [IDL.Opt(AbilitySet)], ['query']),
  'getAvailableAbilities' : IDL.Func([], [IDL.Vec(AbilitySet)], ['query']),
  'getCallerPlayerProfile' : IDL.Func([], [IDL.Opt(PlayerProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPlayerProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PlayerProfile)],
      ['query'],
    ),
  'initializeAbilities' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerPlayerProfile' : IDL.Func([PlayerProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MatchResult = IDL.Record({
    'xpAwarded' : IDL.Nat,
    'didWin' : IDL.Bool,
  });
  const AbilitySet = IDL.Record({
    'id' : IDL.Nat,
    'requiredLevel' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const PlayerProfile = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'level' : IDL.Nat,
    'experience' : IDL.Nat,
    'unlockedAbilities' : IDL.Vec(AbilitySet),
    'avatarUrl' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'awardMatchXp' : IDL.Func([IDL.Bool], [MatchResult], []),
    'getAbilityById' : IDL.Func([IDL.Nat], [IDL.Opt(AbilitySet)], ['query']),
    'getAvailableAbilities' : IDL.Func([], [IDL.Vec(AbilitySet)], ['query']),
    'getCallerPlayerProfile' : IDL.Func(
        [],
        [IDL.Opt(PlayerProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPlayerProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PlayerProfile)],
        ['query'],
      ),
    'initializeAbilities' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerPlayerProfile' : IDL.Func([PlayerProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };